[package]
name = "ml_visual"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# <https://stackoverflow.com/a/74006513/9920172>
crate-type = ["cdylib"]

[dependencies]
